### PR TITLE
Update README with community and build information

### PR DESCRIPTION
**Pull request by karianna**
Add community and build information

### CODE REVIEW

**Review by gdams — APPROVED** [review]
LGTM, can you squash this into one commit and I will merge

**Comment by karianna** [comment]
@gdams I think you can select that option in the Merge Pull Request dropdown?

**Comment by gdams** [comment]
@karianna I'm not sure how things are done in this community, I'm always used to patching commits in rather than using the merge button as I feel that it is cleaner, how do you lot do it?

**Comment by karianna** [comment]
@gdams - Usually the merge function is used (there are CLI tools for this BTW) as that all gets tracked by Git/GitHub (useful meta data for release notes and IP checks etc).  The Dropdown on this GUI gives you the option to either:

1. merge
2. or squash commits and merge
3. or rebase and merge

**Comment by gdams** [comment]
okay that's fine, I'll proceed with merge and advise the others

**Pull request merged**
